[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
newtoday4 = "C2yzwzE7V5dmhRaWmxjNbvtFDNanRjmPUcDtKo6n6kHY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "e7doByN6f3VyrV26aVA3TeNUuMFJ7w22sbUDaK3QNx3.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
