[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
raydium_liquidity = "82p44HjdpEBjebM2KBvP7seVB1RZFVEczBYaeSDUaa7v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "b7doByN6f3VyrV26aVA3TeNUuMFJ7w22sbUDaK3QNx4.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
