[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pda_vesting = "jj96gvB1CD4ei2pRQbCvsB8uHK71aKv1uEKMCKURsMb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "wwaxH9CF9GuHGt7VeMAkEGBDhDaT1QYS6otniQB8wpT.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
