[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pda_vesting = "ku52ZNbaQBkMaQ58pQgZ9xUkTNwpeMWnjZMmLjXYKKp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/macos/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
