[features]
seeds = false
skip-lint = false

[programs.localnet]
btb_finance_clmm = "BTBFiNZy5K4WS9TFYxT8vpRcHBJq3CDf3DTh8NaGDDYP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8" # Raydium CLMM program

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" # SPL Token program

[[test.validator.clone]]
address = "So1endDq2YkqhipRh3WViPa8hdiSpxWy6z3Z6tMCpAo" # Solend program

[workspace]
members = [
    "programs/*"
]

[workspace.dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
solana-program = "~1.17.0"
